default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { localhost } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("DATABASE_USER") { postgres } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { '' } %>

development:
  <<: *default
  database: teebay_backend_development

test:
  <<: *default
  database: teebay_backend_test

production:
  <<: *default
  database: teebay_backend_production
  username: teebay_backend
  password: <%= ENV["TEEBAY_BACKEND_DATABASE_PASSWORD"] %>
